# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0004_watchinggroups_dt_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persongroup',
            name='group',
        ),
        migrations.AddField(
            model_name='persongroup',
            name='group',
            field=models.ManyToManyField(to='vk_app.WatchingGroups'),
        ),
        migrations.AlterField(
            model_name='watchinggroups',
            name='dt_last_update',
            field=models.DateField(default=None, null=True),
        ),
    ]
