# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0008_auto_20170726_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vk_app.Country'),
            preserve_default=False,
        ),
    ]
