# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0009_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='vk_id',
        ),
        migrations.RemoveField(
            model_name='country',
            name='vk_id',
        ),
    ]
