# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0010_auto_20170729_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.WatchingGroups')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.PersonGroup')),
            ],
        ),
        migrations.CreateModel(
            name='LikesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.WatchingGroups')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.PersonGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosPostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateField(auto_now_add=True)),
                ('photo_1280', models.CharField(max_length=255)),
                ('photo_807', models.CharField(max_length=255)),
                ('photo_604', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('dt_create', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.WatchingGroups')),
            ],
        ),
        migrations.CreateModel(
            name='RepostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.WatchingGroups')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.PersonGroup')),
            ],
        ),
        migrations.AddField(
            model_name='photospostgroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.PostGroup'),
        ),
    ]
