# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0011_auto_20170820_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_online', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.PersonGroup')),
            ],
        ),
    ]
