# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0012_persononline'),
    ]

    operations = [
        migrations.AddField(
            model_name='persononline',
            name='is_watching',
            field=models.BooleanField(default=True),
        ),
    ]
