# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0013_persononline_is_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persongroup',
            name='vk_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
