# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0014_auto_20171112_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueGroupUpdating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vk_app.WatchingGroups')),
            ],
        ),
    ]
