# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0015_queuegroupupdating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='commentsgroup',
            name='person',
        ),
        migrations.RemoveField(
            model_name='likesgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='likesgroup',
            name='person',
        ),
        migrations.RemoveField(
            model_name='repostgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='repostgroup',
            name='person',
        ),
        migrations.AddField(
            model_name='postgroup',
            name='comments',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgroup',
            name='likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgroup',
            name='reposts',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgroup',
            name='views',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommentsGroup',
        ),
        migrations.DeleteModel(
            name='LikesGroup',
        ),
        migrations.DeleteModel(
            name='RepostGroup',
        ),
    ]
