# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0016_auto_20171113_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgroup',
            name='vk_id',
            field=models.IntegerField(unique=True),
        ),
    ]
