# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0018_auto_20171113_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachpostgroup',
            name='vk_id',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
