# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0020_auto_20171125_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachpostgroup',
            name='vk_id',
            field=models.IntegerField(),
        ),
    ]
