# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0022_personactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personactions',
            name='dt_create',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='personactions',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watching_group', to='vk_app.WatchingGroups'),
        ),
        migrations.AlterField(
            model_name='personactions',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_group', to='vk_app.PersonGroup'),
        ),
    ]
