# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0023_auto_20180121_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachpostgroup',
            name='vk_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
