# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_app', '0024_auto_20180121_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persongroup',
            name='vk_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postgroup',
            name='vk_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
