# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_status', models.SmallIntegerField(choices=[(0, 'Good'), (1, 'Bad')], default=0)),
                ('ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
            ],
        ),
    ]
