export const USER_INFO = 'USER_INFO';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';

export const GROUP_USERS_INFO = 'GROUP_USERS_INFO';
export const GROUP_USERS_INFO_SUCCESS = 'GROUP_USERS_INFO_SUCCESS';
export const GROUP_USERS_INFO_FAIL = 'GROUP_USERS_INFO_FAIL';