export const USER_INFO = 'USER_INFO';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';
export const USER_INFO_FAIL = 'USER_INFO_FAIL';

export const GROUP_USERS_INFO = 'GROUP_USERS_INFO';
export const GROUP_USERS_INFO_SUCCESS = 'GROUP_USERS_INFO_SUCCESS';
export const GROUP_USERS_INFO_FAIL = 'GROUP_USERS_INFO_FAIL';

export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAIL = 'GET_GROUPS_FAIL';

export const ADD_GROUP = 'ADD_GROUP';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAIL = 'ADD_GROUP_FAIL';

export const GET_GROUP_GEOGRAPHY = 'GET_GROUP_GEOGRAPHY';
export const GET_GROUP_GEOGRAPHY_SUCCESS = 'GET_GROUP_GEOGRAPHY_SUCCESS';
export const GET_GROUP_GEOGRAPHY_FAIL = 'GET_GROUP_GEOGRAPHY_FAIL';

export const GET_GROUP_INTERSECTION = 'GET_GROUP_INTERSECTION';
export const GET_GROUP_INTERSECTION_SUCCESS = 'GET_GROUP_INTERSECTION_SUCCESS';
export const GET_GROUP_INTERSECTION_FAIL = 'GET_GROUP_INTERSECTION_FAIL';

export const GET_GROUP_PEOPLE_ONLINE = 'GET_GROUP_PEOPLE_ONLINE';
export const GET_GROUP_PEOPLE_ONLINE_SUCCESS = 'GET_GROUP_PEOPLE_ONLINE_SUCCESS';
export const GET_GROUP_PEOPLE_ONLINE_FAIL = 'GET_GROUP_PEOPLE_ONLINE_FAIL';

export const GET_GROUP_WALL = 'GET_GROUP_WALL';
export const GET_GROUP_WALL_SUCCESS = 'GET_GROUP_WALL_SUCCESS';
export const GET_GROUP_WALL_FAIL = 'GET_GROUP_WALL_FAIL';

export const GET_GROUP_ACTIONS = 'GET_GROUP_ACTIONS';
export const GET_GROUP_ACTIONS_SUCCESS = 'GET_GROUP_ACTIONS_SUCCESS';
export const GET_GROUP_ACTIONS_FAIL = 'GET_GROUP_ACTIONS_FAIL';